name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install --prefer-offline --no-audit
    - name: Run tests
      run: npx jest
